# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Auto commit

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm run update
      # commit result.json
    - name: Commit result.json
      uses: EndBug/add-and-commit@v4
      with:
        author_name: yanjiaxuan
        author_email: 330544968@qq.com
        message: "AUTO UPDATE SEARCH MAPPER"
        add: "result.json"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}